config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'home/index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :articles

  get 'tagged', to: 'posts#tagged', as: :tagged

  resources :articles do
    resources :comments
  end

  resources :users do
    resources :stories
  end

  resources :tags, only: [:index, :show]

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable
  acts_as_taggable_on :tags
  mount_uploader :feature_image, FeatureImageUploader
  validates :title, presence: true,
                    length: { minimum: 2 }
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @user = current_user
    @stories = @user.stories
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @user = User.find_by(id: params[:user_id])
    @story = Story.find_by(id: params[:id])
  end

  # GET /stories/new
  def new
    @user = User.find_by(id: params[:user_id])
    @story = @user.stories.build
  end

  # GET /stories/1/edit
  def edit
    @user = User.find_by(id: params[:user_id])
    @story = Story.find_by(id: params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @user = User.find_by(id: params[:user_id])
    @story = @user.stories.build(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to [@user, @story], notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    @user = User.find_by(id: params[:user_id])
    @story = Story.find_by(id: params[:id])

    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to [@user, @story], notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tagged
    if params[:tags].present?
      @story = Story.tagged_with(params[:tags])
    else
      @story = Story.postall
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_story
    #   @story = Story.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :description, :tag_list, :feature_image)
    end

end

app/helpers/stories_helper.rb
module StoriesHelper
  # include ActsAsTaggableOn::StoriesHelper
end

app/views/stories/_form.haml
= simple_form_for([@user, @story], html: {id: 'edit-story'}) do |f|
  - if @story.errors.any?
    #error_explanation
      %h2 = pluralize(@story.errors.count, "error") prohibited this story from being saved:

      %ul
      - @story.errors.full_messages.each do |message|
        %li = message

  = f.text_field :title, class: 'title', placeholder: 'Title'
  = f.text_area :description, placeholder: 'Body', data: {provider: 'summernote'}

  .btn-group
    = f.submit 'Save', class: 'btn btn-primary'
  = link_to 'Back', user_stories_path(current_user.id), class: 'btn btn-default'

app/views/stories/_story.html.erb
  <%= story.title %>
  <%= link_to story.title, story %>
  <%= link_to 'Edit', edit_story_path %>

app/views/stories/edit.haml
#story
  = render 'form'

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Stories</h1>

<%= link_to 'New Story', user_stories_path %>

<div class="row">
  <% @stories.each do |story| %>
     <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-4">
       <div class="thumbnail">
        <%= image_tag(story.feature_image_url, :alt => "feature image") %>
        <div class="caption">
          <h3><%= story.title %></h3>
          <p><%= strip_tags story.description %></p>
          <p><%= link_to 'Read more..', user_story_path(@user, story) %></p>
        </div>
      </div>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span></button>
        <ul class="dropdown-menu">
          <li></li>
          <li><%= link_to 'Edit', edit_user_story_path(@user, story) %></li>
          <li><%= link_to 'Destroy', user_story_path(@user, story),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
          </li>
        </div>
      </ul>
    </div>
  <% end %>

</div>

app/views/stories/new.haml
#story
  = render 'form'
  = link_to 'Back', user_stories_path(current_user.id)

app/views/stories/show.haml
%p#notice
  - if flash[:notice]
    .alert.alert-success{role:'alert'}
      = notice
= @story.title
= @story.description.html_safe
= link_to 'Edit', edit_user_story_path(@user, @story)
- @story.tags.any?
  - @story.tags.each do |tag|
  = tag.name
  = link_to tag.name, tag_path(tag)