config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'home/index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :articles

  get 'tagged', to: 'posts#tagged', as: :tagged

  resources :articles do
    resources :comments
  end

  resources :users do
    resources :stories
  end

  resources :tags, only: [:index, :show]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Typebase
  </small>
</footer>

app/views/layouts/_header.haml
- if logged_in?
  = gravatar_for current_user
  %p.current-user-name
    = current_user.name
%nav
  %ul.nav.nav-stacked
    %li= link_to "Home",   root_path
    %li= link_to "Sign up", signup_path
    %li= link_to "Read", ""
    - if logged_in?
      %li= link_to 'Start writing', new_user_story_path(current_user.id)
    - else
      %li= link_to 'Start writing', ''
    - if logged_in?
      %li= link_to 'My Novels', user_stories_path(current_user.id)
      %li= link_to "Users", users_path
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          Account
          %b.caret
        %ul.dropdown-menu
          %li= link_to "Profile", current_user
          %li= link_to "Settings", '#'
          %li.divider
          %li
            = link_to "Log out", logout_path, method: "delete"
    - else
      %li= link_to "Log in", login_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
    'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>
  <div class="page-wrapper">
    <div class="hero-navigation">
      <%= render 'layouts/header' %>
    </div>

    <div class="view">
      <div class="content">
          <% flash.each do |message_type, message| %>
              <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
          <% end %>
          <section>
              <%= yield %>
          </section>
          <%= render 'layouts/footer' %>
          <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </div>
</body>
</html>